# Generated by Django 2.2 on 2019-11-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id_user', models.AutoField(primary_key=True, serialize=False)),
                ('Nickname', models.CharField(db_index=True, max_length=20)),
                ('Password', models.CharField(max_length=32)),
                ('Device', models.CharField(db_index=True, max_length=100)),
                ('Name', models.CharField(max_length=20)),
                ('Money', models.IntegerField()),
            ],
        ),
    ]
