# Generated by Django 2.2 on 2019-11-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
