# Generated by Django 2.2 on 2019-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20191107_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('Id_author', models.AutoField(primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Id_book', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=60)),
                ('Body', models.TextField(blank=True, db_index=True)),
                ('Picture', models.ImageField(blank=True, upload_to='')),
                ('File', models.FileField(blank=True, upload_to='')),
                ('Authors', models.ManyToManyField(related_name='books', to='server.Authors')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='Books',
            field=models.ManyToManyField(blank=True, related_name='users', to='server.Books'),
        ),
    ]
