# Generated by Django 2.2 on 2019-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20191107_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Cost',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
