# Generated by Django 2.2 on 2019-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20191108_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='Slug',
            field=models.SlugField(max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='Slug',
            field=models.SlugField(max_length=30),
            preserve_default=False,
        ),
    ]
