# Generated by Django 2.2 on 2019-11-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20191108_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='Slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='Slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
