# Generated by Django 2.2 on 2019-11-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_users_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
