# Generated by Django 2.2 on 2019-11-10 09:53

from django.db import migrations, models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20191109_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='Slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='File',
            field=models.FileField(blank=True, upload_to='media/files/', validators=[server.validators.validate_file]),
        ),
        migrations.AlterField(
            model_name='books',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='media/pictures/', validators=[server.validators.validate_picture]),
        ),
        migrations.AlterField(
            model_name='books',
            name='Slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='Slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
