# Generated by Django 2.2 on 2019-11-10 10:07

from django.db import migrations, models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20191110_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='File',
            field=models.FileField(blank=True, upload_to='files/', validators=[server.validators.validate_file]),
        ),
        migrations.AlterField(
            model_name='books',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='pictures/', validators=[server.validators.validate_picture]),
        ),
    ]
