# Generated by Django 2.2 on 2019-11-10 11:35

from django.db import migrations, models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20191110_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Picture',
            field=models.ImageField(upload_to='pictures/', validators=[server.validators.validate_picture]),
        ),
    ]
